plugins {
    id 'com.android.application'
}

android {
    signingConfigs {
        debug {
            if (file('D:\\AndroidStudioProjects\\mWord.jks').exists()) {
                storeFile file('D:\\AndroidStudioProjects\\mWord.jks')
                storePassword '200976Mk'
                keyAlias 'key0'
                keyPassword '200976Mk'
            }
        }
    }
    compileSdk 33
    def dateFormat = new Date().format('ddMMMyy_HHmm')
    defaultConfig {
        applicationId 'com.mke.mword'
        minSdk 21
        targetSdk 33
        versionCode 51
        versionName "1.0"
        multiDexEnabled true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        setProperty("archivesBaseName", applicationId + "_v" + versionName + "(" + versionCode + ")_"+dateFormat)
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            signingConfig signingConfigs.debug
        }
        // add the code from below line.
        applicationVariants.all{
                // this method is use to rename your release apk only
            variant ->
                variant.outputs.each{
                        // on below line we are setting a name to our apk
                    output->
                        // on below line we are specifying our app name.
                        project.ext { appName = 'mWord' }
                        // on below line we are adding the formatted date to our apk file name.
                        def formattedDate = new Date().format('yyyy-MM-dd-HH-mm-ss')
                        // on below line we are creating a new name for our apk.
                        def newName = output.outputFile.name
                        // on below line we are replacing our previous name with our app name.
                        newName = newName.replace("app-", "$project.ext.appName-")
                        // on below line we are replacing -release with our formatted date.
                        newName = newName.replace("-release", "-release-" + formattedDate)
                        // at last we are setting our apk name to it.
                        output.outputFileName = newName
                }
        }
    }
    lintOptions {
        checkReleaseBuilds false
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildFeatures {
        viewBinding true
    }
    packagingOptions {
        exclude 'META-INF/services/javax.annotation.processing.Processor'
    }

}

dependencies {

    implementation 'androidx.appcompat:appcompat:1.4.1'
    implementation 'com.google.android.material:material:1.5.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.3'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'

    implementation 'com.google.android.play:core:1.10.3'//for new version updater'
    implementation 'com.android.billingclient:billing:4.1.0'
    implementation files('libs/mail.jar')
    implementation files('libs/activation.jar')
    implementation files('libs/additionnal.jar')
    implementation files('libs/itextpdf-5.4.3.jar')

    implementation 'com.squareup.picasso:picasso:2.71828'

    implementation 'com.google.android.exoplayer:exoplayer:2.18.7'
    implementation 'org.jsoup:jsoup:1.14.3'

    implementation 'com.github.HaarigerHarald:android-youtubeExtractor:master-SNAPSHOT'

    implementation 'com.github.bumptech.glide:glide:4.13.1'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.13.1'
    implementation 'androidx.recyclerview:recyclerview:1.3.0-alpha01'
}